# -*- coding: utf-8 -*-
"""ML_CLUSTERING.ipyb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1v4HFIcRvuiQ3T4n_WjSmKrgh4D_wpw4H
"""

import pandas as pd
from sklearn.cluster import DBSCAN, KMeans, AgglomerativeClustering
import matplotlib.pyplot as plt
import seaborn as sns

"""### Muat Dataset

Memuat dataset `wellnes1.csv` ke dalam DataFrame pandas.
"""

df = pd.read_csv('/content/drive/MyDrive/ML_MID/wellnes1.csv', sep=';')

"""### Eksplorasi Data

Mari kita mulai dengan melihat beberapa baris pertama, informasi tentang kolom, dan statistik deskriptif.
"""

print("First 5 rows of the dataset:")
display(df.head())

print("\nDataset Information:")
df.info()

print("\nDescriptive Statistics:")
display(df.describe())

"""### Nilai Hilang

Sekarang, mari kita periksa apakah ada nilai yang hilang dalam dataset.
"""

print("\nMissing values per column:")
display(df.isnull().sum())

print("\nPercentage of missing values per column:")
display(df.isnull().sum() / len(df) * 100)

"""### Box Plot untuk Fitur Numerik

Mari kita visualisasikan distribusi setiap fitur numerik menggunakan box plot. Ini akan membantu dalam memahami sebaran data dan mengidentifikasi *outlier* (pencilan).
"""

import matplotlib.pyplot as plt
import seaborn as sns

# Identify numerical columns (all columns are numerical in this dataset)
numerical_cols = df.columns

# Set up the matplotlib figure and axes for subplots
num_features = len(numerical_cols)
num_rows = (num_features + 2) // 3 # Roughly 3 plots per row
num_cols = 3

fig, axes = plt.subplots(num_rows, num_cols, figsize=(18, num_rows * 5))
axes = axes.flatten() # Flatten the 2D array of axes for easy iteration

for i, col in enumerate(numerical_cols):
    # Using 'color' instead of 'palette' for single boxplots to avoid FutureWarning
    sns.boxplot(y=df[col], ax=axes[i], color='skyblue')
    axes[i].set_title(f'Box Plot of {col}')
    axes[i].set_ylabel('') # Remove y-label to avoid clutter, title is sufficient

# Hide any unused subplots
for j in range(i + 1, len(axes)):
    fig.delaxes(axes[j])

plt.tight_layout()
plt.show()

"""### Heatmap Korelasi

Mari kita visualisasikan matriks korelasi fitur-fitur yang sudah diskalakan untuk memahami hubungan antar fitur. Ini dapat membantu mengidentifikasi fitur-fitur yang sangat berkorelasi yang mungkin mempengaruhi hasil klastering.
"""

# Identify the original 10 features from the initial dataset load
original_features = ['screen_time_hours', 'work_screen_hours', 'leisure_screen_hours', 'sleep_hours',
                     'sleep_quality_1_5', 'stress_level_0_10', 'productivity_0_100',
                     'exercise_minutes_per_week', 'social_hours_per_week', 'mental_wellness_index_0_100']

# Calculate the correlation matrix for only these original features
corr_matrix = df[original_features].corr()

# Set up the matplotlib figure
plt.figure(figsize=(12, 10))

# Draw the heatmap with the mask and correct aspect ratio
sns.heatmap(corr_matrix, annot=True, cmap='coolwarm', fmt='.2f', linewidths=.5)
plt.title('Correlation Heatmap of the 10 Original Dataset Features')
plt.show()

"""### Pemilihan Fitur untuk Klastering

Berdasarkan permintaan Anda, kita akan memilih fitur-fitur berikut untuk klastering: `stress_level_0_10`, `productivity_0_100`, `sleep_quality_1_5`, dan `screen_time_hours`. Fitur-fitur ini akan menjadi dasar analisis klastering kita.
"""

selected_features = ['stress_level_0_10', 'productivity_0_100', 'sleep_quality_1_5', 'screen_time_hours']
df_selected = df[selected_features]

print("First 5 rows of the selected features for clustering:")
display(df_selected.head())

"""### Pemilihan Fitur

Untuk analisis ini, kita akan menggunakan semua fitur numerik yang tersedia. Semua kolom tampak relevan untuk memahami berbagai aspek kesejahteraan dan potensi hubungannya dalam klastering.

### Skala Fitur

Algoritma klastering, terutama yang berbasis jarak seperti K-Means dan DBSCAN, sensitif terhadap skala fitur. Untuk memastikan bahwa semua fitur berkontribusi secara merata pada perhitungan jarak, kita akan menskalakan data menggunakan `StandardScaler`.
"""

from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()

df_scaled = scaler.fit_transform(df_selected)
df_scaled = pd.DataFrame(df_scaled, columns=selected_features)

print("First 5 rows:")
display(df_scaled.head())

"""### Menentukan Klaster Optimal menggunakan Metode Elbow (K-Means)

Untuk menemukan jumlah klaster (k) yang optimal untuk K-Means, kita akan menggunakan metode Elbow. Metode ini melibatkan perhitungan *Within-Cluster Sum of Squares* (WCSS) untuk nilai k yang berbeda. WCSS mengukur jumlah jarak kuadrat antara setiap titik dan centroid dalam sebuah klaster.

Kita membuat plot WCSS terhadap jumlah klaster (k). Titik 'siku' pada plot, di mana laju penurunan WCSS melambat secara signifikan, sering dianggap sebagai k yang optimal.
"""

wcss = []
k_range = range(2, 11) # K from 2 to 10

for k in k_range:
    kmeans = KMeans(n_clusters=k, random_state=42, n_init=10) # Set n_init to suppress warning
    kmeans.fit(df_scaled)
    wcss.append(kmeans.inertia_)

# Plotting the Elbow Method
plt.figure(figsize=(10, 6))
plt.plot(k_range, wcss, marker='o', linestyle='--')
plt.title('Elbow Method for Optimal K')
plt.xlabel('Number of Clusters (K)')
plt.ylabel('Within-Cluster Sum of Squares (WCSS)')
plt.xticks(k_range)
plt.grid(True)
plt.show()

"""### Skor Silhouette untuk K Optimal (K-Means)

Selain metode Elbow, kita bisa menggunakan Skor Silhouette untuk menentukan jumlah klaster optimal. Skor Silhouette adalah ukuran seberapa mirip suatu objek dengan klaster sendiri (kohesi) dibandingkan dengan klaster tetangga lainnya (pemisahan).

*   Skor mendekati +1 menunjukkan bahwa objek sangat cocok dengan klaster sendiri dan kurang cocok dengan klaster tetangga.
*   Skor mendekati 0 menunjukkan bahwa objek berada di atau sangat dekat dengan batas keputusan antara dua klaster tetangga.
*   Skor mendekati -1 menunjukkan bahwa objek mungkin telah salah diklasifikasikan ke klaster yang salah.
"""

from sklearn.metrics import silhouette_score

silhouette_scores = []

for k in k_range:
    kmeans = KMeans(n_clusters=k, random_state=42, n_init=10)
    cluster_labels = kmeans.fit_predict(df_scaled)
    silhouette_avg = silhouette_score(df_scaled, cluster_labels)
    silhouette_scores.append(silhouette_avg)

# Plotting the Silhouette Scores
plt.figure(figsize=(10, 6))
plt.plot(k_range, silhouette_scores, marker='o', linestyle='--')
plt.title('Silhouette Scores for Optimal K')
plt.xlabel('Number of Clusters (K)')
plt.ylabel('Silhouette Score')
plt.xticks(k_range)
plt.grid(True)
plt.show()

# Display the scores
for k, score in zip(k_range, silhouette_scores):
    print(f"For K = {k}, Silhouette Score = {score:.4f}")

"""### Menerapkan K-Means dengan K=2 dan Visualisasi

Berdasarkan Skor Silhouette yang dihitung, K=2 menghasilkan skor tertinggi. Mari kita terapkan algoritma K-Means dengan K=2 pada fitur-fitur yang kita pilih dan visualisasikan hasil klasteringnya.
"""

import numpy as np

# Set K to 2 for this analysis
optimal_k_2 = 2

print(f"Applying K-Means with K={optimal_k_2}")

# Apply K-Means with K=2
kmeans_k2 = KMeans(n_clusters=optimal_k_2, random_state=42, n_init=10)
df['cluster_kmeans_k2'] = kmeans_k2.fit_predict(df_scaled)

print("\nFirst 5 rows of the dataset with K-Means K=2 cluster labels:")
display(df.head())

# Calculate and display the final Silhouette Score for K=2
final_silhouette_score_k2 = silhouette_score(df_scaled, df['cluster_kmeans_k2'])
print(f"\nFinal Silhouette Score for K={optimal_k_2}: {final_silhouette_score_k2:.4f}")

"""### Memvisualisasikan Hasil Klastering K-Means (K=2) menggunakan PCA

Untuk memvisualisasikan 2 klaster ini dalam ruang 2D, kita akan menggunakan Analisis Komponen Utama (PCA).
"""

from sklearn.decomposition import PCA

# Apply PCA to reduce to 2 components for visualization
pca_k2 = PCA(n_components=2)
df_pca_k2 = pca_k2.fit_transform(df_scaled)

# Create a DataFrame for the PCA results
df_pca_k2 = pd.DataFrame(data=df_pca_k2, columns=['Principal Component 1', 'Principal Component 2'])

# Add the cluster labels to the PCA DataFrame
df_pca_k2['cluster'] = df['cluster_kmeans_k2']

# Plotting the PCA results
plt.figure(figsize=(10, 8))
sns.scatterplot(
    x='Principal Component 1',
    y='Principal Component 2',
    hue='cluster',
    palette='viridis',
    data=df_pca_k2,
    s=100,
    alpha=0.7,
    edgecolor='w'
)
plt.title(f'K-Means Clustering (K={optimal_k_2}) Visualization with PCA')
plt.xlabel('Principal Component 1')
plt.ylabel('Principal Component 2')
plt.grid(True)
plt.legend(title='Cluster')
plt.show()

"""### Ringkasan Hasil Klastering K-Means (K=2)

Berdasarkan analisis, klastering K-Means diterapkan dengan **K=2**, yang menghasilkan Skor Silhouette **0.4627**. Visualisasi ini membantu dalam memahami pemisahan dua klaster yang teridentifikasi dalam ruang 2D setelah reduksi dimensi dengan PCA.

### Inferensi dari Klastering K-Means (K=2)

Mari kita analisis karakteristik dari masing-masing dua klaster K-Means dengan melihat nilai rata-rata dari fitur-fitur asli, terutama `mental_wellness_index_0_100`.
"""

print('Nilai rata-rata fitur per klaster K-Means (K=2):')
display(df.groupby('cluster_kmeans_k2')[selected_features + ['mental_wellness_index_0_100']].mean().round(2))

# Analisis detail untuk klaster K-Means
cluster_kmeans_k2_summary = df.groupby('cluster_kmeans_k2')[selected_features + ['mental_wellness_index_0_100']].mean().round(2)

print('\nInterpretasi Detail Klaster K-Means (K=2):')
for i, row in cluster_kmeans_k2_summary.iterrows():
    print(f'\n--- Klaster {i} ---')
    print(f"Tingkat Stres Rata-rata: {row['stress_level_0_10']:.2f}")
    print(f"Produktivitas Rata-rata: {row['productivity_0_100']:.2f}")
    print(f"Kualitas Tidur Rata-rata (1-5): {row['sleep_quality_1_5']:.2f}")
    print(f"Waktu Layar Rata-rata (jam): {row['screen_time_hours']:.2f}")
    print(f"Indeks Kesejahteraan Mental Rata-rata (0-100): {row['mental_wellness_index_0_100']:.2f}")

    # Logika yang diperbaiki untuk interpretasi
    if i == 0: # Klaster 0 sekarang sesuai dengan 'Sehat dan Berkinerja Tinggi' berdasarkan rata-rata
        print("\n**Interpretasi: Kelompok 'Sehat dan Berkinerja Tinggi'**")
        print("Klaster ini mewakili individu yang umumnya mengalami **kesejahteraan mental yang tinggi**.")
        print(f"Mereka cenderung memiliki **tingkat stres rata-rata rendah** ({row['stress_level_0_10']:.2f}) dan **produktivitas tinggi** ({row['productivity_0_100']:.2f}).")
        print(f"**Kualitas tidur mereka juga baik** ({row['sleep_quality_1_5']:.2f}), berkontribusi pada kondisi mental mereka secara keseluruhan.")
        print(f"Selain itu, **waktu layar mereka relatif rendah** ({row['screen_time_hours']:.2f} jam), menunjukkan gaya hidup seimbang yang mendukung kesejahteraan mental.")
        print("Kelompok ini kemungkinan besar mengelola tuntutan harian secara efektif, mengarah pada kondisi mental yang lebih sehat.")
    elif i == 1: # Klaster 1 sekarang sesuai dengan 'Stres dan Berjuang' berdasarkan rata-rata
        print("\n**Interpretasi: Kelompok 'Stres dan Berjuang'**")
        print("Klaster ini ditandai dengan **kesejahteraan mental yang secara signifikan lebih rendah**.")
        print(f"Individu di sini menunjukkan **tingkat stres rata-rata tinggi** ({row['stress_level_0_10']:.2f}), yang kemungkinan memengaruhi **produktivitas mereka yang lebih rendah** ({row['productivity_0_100']:.2f}).")
        print(f"Faktor kritis adalah **kualitas tidur mereka yang buruk** ({row['sleep_quality_1_5']:.2f}), yang seringkali menjadi gejala dan kontributor stres yang meningkat serta kesejahteraan mental yang berkurang.")
        print(f"**Waktu layar mereka relatif tinggi** ({row['screen_time_hours']:.2f} jam), berpotensi berkontribusi pada stres keseluruhan dan penurunan kualitas tidur mereka.")
        print("Kelompok ini menghadapi tantangan besar dalam menjaga kesehatan mental mereka karena kombinasi faktor-faktor ini.")

"""### Menerapkan K-Means dengan K Optimal dan Visualisasi

Berdasarkan Skor Silhouette yang dihitung, kita akan memilih jumlah klaster (`K`) yang menghasilkan skor tertinggi. Kemudian, kita akan menerapkan algoritma K-Means dengan `K` optimal ini pada fitur-fitur yang kita pilih. Terakhir, kita akan memvisualisasikan hasil klastering untuk memeriksa pemisahan dan distribusi klaster.
"""

import numpy as np

# User requested to change from K=2 and not use the second best (K=5).
# The next best Silhouette Score is for K=4.
optimal_k = 4

print(f"Optimal K based on user request: {optimal_k}")

# Apply K-Means with the chosen K
kmeans_optimal = KMeans(n_clusters=optimal_k, random_state=42, n_init=10)
df['cluster_kmeans'] = kmeans_optimal.fit_predict(df_scaled)

print("\nFirst 5 rows of the dataset with K-Means cluster labels:")
display(df.head())

# Calculate and display the final Silhouette Score for the optimal K
final_silhouette_score = silhouette_score(df_scaled, df['cluster_kmeans'])
print(f"\nFinal Silhouette Score for K={optimal_k}: {final_silhouette_score:.4f}")

"""### Memvisualisasikan Hasil Klastering K-Means (K Optimal) menggunakan PCA

Untuk memvisualisasikan klaster dalam ruang 2D, kita akan menggunakan Analisis Komponen Utama (PCA). PCA adalah teknik reduksi dimensi yang mengubah serangkaian variabel yang berkorelasi menjadi serangkaian variabel yang tidak berkorelasi yang lebih kecil yang disebut komponen utama. Komponen-komponen ini menangkap sebagian besar variansi dalam data, memungkinkan kita untuk merepresentasikan data berdimensi tinggi dalam dimensi yang lebih rendah sambil mempertahankan informasi sebanyak mungkin.

### Memvisualisasikan Hasil Klastering K-Means menggunakan PCA

Untuk memvisualisasikan klaster dalam ruang 2D, kita akan menggunakan Analisis Komponen Utama (PCA). PCA adalah teknik reduksi dimensi yang mengubah serangkaian variabel yang berkorelasi menjadi serangkaian variabel yang tidak berkorelasi yang lebih kecil yang disebut komponen utama. Komponen-komponen ini menangkap sebagian besar variansi dalam data, memungkinkan kita untuk merepresentasikan data berdimensi tinggi dalam dimensi yang lebih rendah sambil mempertahankan informasi sebanyak mungkin.
"""

from sklearn.decomposition import PCA

# Apply PCA to reduce to 2 components for visualization
pca = PCA(n_components=2)
df_pca = pca.fit_transform(df_scaled)

# Create a DataFrame for the PCA results
df_pca = pd.DataFrame(data=df_pca, columns=['Principal Component 1', 'Principal Component 2'])

# Add the cluster labels to the PCA DataFrame
df_pca['cluster'] = df['cluster_kmeans']

# Plotting the PCA results
plt.figure(figsize=(10, 8))
sns.scatterplot(
    x='Principal Component 1',
    y='Principal Component 2',
    hue='cluster',
    palette='viridis',
    data=df_pca,
    s=100,
    alpha=0.7,
    edgecolor='w'
)
plt.title(f'K-Means Clustering (K={optimal_k}) Visualization with PCA')
plt.xlabel('Principal Component 1')
plt.ylabel('Principal Component 2')
plt.grid(True)
plt.legend(title='Cluster')
plt.show()

from sklearn.decomposition import PCA

# Apply PCA to reduce to 2 components for visualization
pca = PCA(n_components=2)
df_pca = pca.fit_transform(df_scaled)

# Create a DataFrame for the PCA results
df_pca = pd.DataFrame(data=df_pca, columns=['Principal Component 1', 'Principal Component 2'])

# Add the cluster labels to the PCA DataFrame
df_pca['cluster'] = df['cluster_kmeans']

# Plotting the PCA results
plt.figure(figsize=(10, 8))
sns.scatterplot(
    x='Principal Component 1',
    y='Principal Component 2',
    hue='cluster',
    palette='viridis',
    data=df_pca,
    s=100,
    alpha=0.7,
    edgecolor='w'
)
plt.title(f'K-Means Clustering (K={optimal_k}) Visualization with PCA')
plt.xlabel('Principal Component 1')
plt.ylabel('Principal Component 2')
plt.grid(True)
plt.legend(title='Cluster')
plt.show()

"""### Ringkasan Hasil Klastering K-Means (K=4)

Berdasarkan analisis, klastering K-Means diterapkan dengan **K=4**, yang menghasilkan Skor Silhouette **0.3859**. Visualisasi ini membantu dalam memahami pemisahan empat klaster yang teridentifikasi dalam ruang 2D setelah reduksi dimensi dengan PCA.

### Inferensi dari Klastering K-Means (K=4)

Mari kita analisis karakteristik dari masing-masing empat klaster K-Means dengan melihat nilai rata-rata dari fitur-fitur asli, terutama `mental_wellness_index_0_100`.
"""

print('Mean values of features per K-Means cluster:')
display(df.groupby('cluster_kmeans')[selected_features + ['mental_wellness_index_0_100']].mean().round(2))

# Detailed analysis for K-Means clusters
cluster_kmeans_summary = df.groupby('cluster_kmeans')[['stress_level_0_10', 'productivity_0_100', 'sleep_quality_1_5', 'mental_wellness_index_0_100']].mean().round(2)

print('\nInterpretation of K-Means Clusters:')
for i, row in cluster_kmeans_summary.iterrows():
    print(f'\n--- Cluster {i} ---')
    print(f"Average Stress Level: {row['stress_level_0_10']}")
    print(f"Average Productivity: {row['productivity_0_100']}")
    print(f"Average Sleep Quality: {row['sleep_quality_1_5']}")
    print(f"Average Mental Wellness Index: {row['mental_wellness_index_0_100']}")

    # Provide an interpretation based on the values
    if row['mental_wellness_index_0_100'] > 70:
        print("This cluster generally exhibits high mental wellness.")
    elif row['mental_wellness_index_0_100'] > 50:
        print("This cluster generally exhibits moderate mental wellness.")
    else:
        print("This cluster generally exhibits lower mental wellness.")

    if row['stress_level_0_10'] > 7:
        print("High stress levels are typical in this group.")
    elif row['stress_level_0_10'] < 4:
        print("Low stress levels are typical in this group.")

    if row['productivity_0_100'] > 70:
        print("High productivity is a common trait.")
    elif row['productivity_0_100'] < 40:
        print("Lower productivity is a common trait.")

    if row['sleep_quality_1_5'] > 3:
        print("Good sleep quality is observed.")
    elif row['sleep_quality_1_5'] < 2:
        print("Poor sleep quality is observed.")

"""### 2 **Klastering Aglomeratif**
Sekarang, mari kita jelajahi Klastering Aglomeratif, yang merupakan jenis klastering hierarkis. Kita akan menguji berbagai jumlah klaster (dari 2 hingga 10) dan berbagai metode linkage ('ward', 'complete', 'average') untuk menemukan konfigurasi terbaik berdasarkan Skor Silhouette.
"""

from sklearn.metrics import silhouette_score
from sklearn.cluster import AgglomerativeClustering
import numpy as np

# Define the range of clusters and linkage methods to test
k_range = range(2, 11) # K from 2 to 10
linkage_methods = ['ward', 'complete', 'average']

# Dictionary to store silhouette scores for each combination
silhouette_results = {}

# Iterate through linkage methods and number of clusters
for linkage in linkage_methods:
    scores_for_linkage = []
    for k in k_range:
        # 'ward' linkage only works with Euclidean distance and n_clusters > 1
        if linkage == 'ward' and k == 1:
            continue

        # Apply Agglomerative Clustering
        agg_clustering = AgglomerativeClustering(n_clusters=k, linkage=linkage)
        cluster_labels = agg_clustering.fit_predict(df_scaled)

        # Calculate Silhouette Score
        score = silhouette_score(df_scaled, cluster_labels)
        scores_for_linkage.append(score)
    silhouette_results[linkage] = scores_for_linkage

# Print the results
print("Silhouette Scores for Agglomerative Clustering:")
for linkage, scores in silhouette_results.items():
    print(f"Linkage Method: {linkage}")
    for i, score in enumerate(scores):
        print(f"  K = {k_range[i]}, Silhouette Score = {score:.4f}")

# Find the best parameters
best_score = -1
best_k = -1
best_linkage = ''

for linkage, scores in silhouette_results.items():
    for i, score in enumerate(scores):
        if score > best_score:
            best_score = score
            best_k = k_range[i]
            best_linkage = linkage

print(f"\nBest Agglomerative Clustering Model:")
print(f"  Optimal K = {best_k}")
print(f"  Optimal Linkage = {best_linkage}")
print(f"  Highest Silhouette Score = {best_score:.4f}")

"""### Menerapkan Model Klastering Aglomeratif Terbaik dan Visualisasi

Berdasarkan Skor Silhouette, kita sekarang akan menerapkan model Klastering Aglomeratif terbaik dan memvisualisasikan hasilnya menggunakan PCA.
"""

# Apply Agglomerative Clustering with the best parameters
best_agg_clustering = AgglomerativeClustering(n_clusters=best_k, linkage=best_linkage)
df['cluster_agglomerative'] = best_agg_clustering.fit_predict(df_selected)

print(f"Agglomerative Clustering applied with K={best_k} and linkage='{best_linkage}'.")
print("\nFirst 5 rows of the dataset with Agglomerative cluster labels:")
display(df.head())

# Prepare data for PCA visualization
pca = PCA(n_components=2)
df_pca_agg = pca.fit_transform(df_scaled)
df_pca_agg = pd.DataFrame(data=df_pca_agg, columns=['Principal Component 1', 'Principal Component 2'])
df_pca_agg['cluster'] = df['cluster_agglomerative']

# Plotting the PCA results for Agglomerative Clustering
plt.figure(figsize=(10, 8))
sns.scatterplot(
    x='Principal Component 1',
    y='Principal Component 2',
    hue='cluster',
    palette='viridis',
    data=df_pca_agg,
    s=100,
    alpha=0.7,
    edgecolor='w'
)
plt.title(f'Agglomerative Clustering (K={best_k}, Linkage={best_linkage}) Visualization with PCA')
plt.xlabel('Principal Component 1')
plt.ylabel('Principal Component 2')
plt.grid(True)
plt.legend(title='Cluster')
plt.show()

"""### Eksplorasi Klastering Aglomeratif dengan K=3

Untuk mendapatkan perspektif tambahan, mari kita terapkan Klastering Aglomeratif dengan 3 klaster, menggunakan metode 'average' linkage, dan memvisualisasikan hasilnya dengan PCA.
"""

from sklearn.cluster import AgglomerativeClustering
from sklearn.decomposition import PCA
import matplotlib.pyplot as plt
import seaborn as sns

# Apply Agglomerative Clustering with K=3 and 'average' linkage
agg_clustering_k3 = AgglomerativeClustering(n_clusters=3, linkage='average')
df['cluster_agglomerative_k3'] = agg_clustering_k3.fit_predict(df_scaled)

print(f"Agglomerative Clustering applied with K=3 and linkage='average'.")
print("\nFirst 5 rows of the dataset with Agglomerative K=3 cluster labels:")
display(df.head())

# Prepare data for PCA visualization
pca_k3 = PCA(n_components=2)
df_pca_agg_k3 = pca_k3.fit_transform(df_scaled)
df_pca_agg_k3 = pd.DataFrame(data=df_pca_agg_k3, columns=['Principal Component 1', 'Principal Component 2'])
df_pca_agg_k3['cluster'] = df['cluster_agglomerative_k3']

# Plotting the PCA results for Agglomerative Clustering with K=3
plt.figure(figsize=(10, 8))
sns.scatterplot(
    x='Principal Component 1',
    y='Principal Component 2',
    hue='cluster',
    palette='viridis',
    data=df_pca_agg_k3,
    s=100,
    alpha=0.7,
    edgecolor='w'
)
plt.title(f'Agglomerative Clustering (K=3, Linkage=average) Visualization with PCA')
plt.xlabel('Principal Component 1')
plt.ylabel('Principal Component 2')
plt.grid(True)
plt.legend(title='Cluster')
plt.show()

"""### Ringkasan Hasil Klastering Aglomeratif

Berdasarkan eksplorasi berbagai konfigurasi, Klastering Aglomeratif dengan **K=3** dan **'average' linkage** akan menjadi fokus analisis lebih lanjut, meskipun K=2 memiliki Skor Silhouette yang sedikit lebih tinggi. Konfigurasi K=3 ini menghasilkan Skor Silhouette **0.4368**.

### Inferensi dari Klastering Aglomeratif (K=3, Linkage='average')

Mari kita telaah karakteristik dari ketiga klaster Aglomeratif ini dan bagaimana mereka berkaitan dengan kesehatan mental.
"""

print('Mean values of features per Agglomerative cluster:')
display(df.groupby('cluster_agglomerative')[selected_features + ['mental_wellness_index_0_100']].mean().round(2))

# Detailed analysis for Agglomerative clusters
cluster_agg_summary = df.groupby('cluster_agglomerative')[['stress_level_0_10', 'productivity_0_100', 'sleep_quality_1_5', 'mental_wellness_index_0_100']].mean().round(2)

print('\nInterpretation of Agglomerative Clusters:')
for i, row in cluster_agg_summary.iterrows():
    print(f'\n--- Cluster {i} ---')
    print(f"Average Stress Level: {row['stress_level_0_10']}")
    print(f"Average Productivity: {row['productivity_0_100']}")
    print(f"Average Sleep Quality: {row['sleep_quality_1_5']}")
    print(f"Average Mental Wellness Index: {row['mental_wellness_index_0_100']}")

    if row['mental_wellness_index_0_100'] > 70:
        print("This cluster generally exhibits high mental wellness.")
    elif row['mental_wellness_index_0_100'] > 50:
        print("This cluster generally exhibits moderate mental wellness.")
    else:
        print("This cluster generally exhibits lower mental wellness.")

    if row['stress_level_0_10'] > 7:
        print("High stress levels are typical in this group.")
    elif row['stress_level_0_10'] < 4:
        print("Low stress levels are typical in this group.")

    if row['productivity_0_100'] > 70:
        print("High productivity is a common trait.")
    elif row['productivity_0_100'] < 40:
        print("Lower productivity is a common trait.")

    if row['sleep_quality_1_5'] > 3:
        print("Good sleep quality is observed.")
    elif row['sleep_quality_1_5'] < 2:
        print("Poor sleep quality is observed.")

"""### Klastering DBSCAN

Sekarang, mari kita jelajahi DBSCAN (*Density-Based Spatial Clustering of Applications with Noise*). DBSCAN adalah algoritma klastering non-parametrik berbasis densitas yang dapat menemukan klaster dengan bentuk arbitrer dan mendeteksi titik noise. Algoritma ini membutuhkan dua parameter utama:

*   **`eps` (epsilon):** Jarak maksimum antara dua sampel agar salah satunya dianggap berada di lingkungan yang lain.
*   **`min_samples`:** Jumlah sampel (atau total bobot) dalam lingkungan agar sebuah titik dianggap sebagai titik inti. Ini termasuk titik itu sendiri.

Kita akan menguji berbagai kombinasi `eps` dan `min_samples` untuk menemukan konfigurasi terbaik berdasarkan Skor Silhouette. Perlu dicatat bahwa titik-titik yang diklasifikasikan sebagai *noise* oleh DBSCAN (label klaster -1) tidak akan dimasukkan dalam perhitungan Skor Silhouette.
"""

from sklearn.cluster import DBSCAN
from sklearn.metrics import silhouette_score
import numpy as np

# Define parameter ranges to test
eps_range = np.arange(0.3, 1.6, 0.1) # from 0.3 to 1.5
min_samples_range = range(3, 11) # from 3 to 10

# Dictionary to store silhouette scores for each combination
dbscan_silhouette_results = {}

best_dbscan_score = -1
best_dbscan_eps = -1
best_dbscan_min_samples = -1

# Iterate through eps and min_samples
for eps in eps_range:
    for min_samples in min_samples_range:
        dbscan = DBSCAN(eps=eps, min_samples=min_samples)
        cluster_labels = dbscan.fit_predict(df_scaled)

        # Filter out noise points for Silhouette Score calculation
        unique_labels = set(cluster_labels)
        if -1 in unique_labels: # Remove noise if present
            unique_labels.remove(-1)

        # Only calculate Silhouette Score if more than one cluster is found (excluding noise)
        if len(unique_labels) > 1:
            # Get indices of non-noise points
            non_noise_indices = cluster_labels != -1
            score = silhouette_score(df_scaled[non_noise_indices], cluster_labels[non_noise_indices])

            dbscan_silhouette_results[(eps, min_samples)] = score

            if score > best_dbscan_score:
                best_dbscan_score = score
                best_dbscan_eps = eps
                best_dbscan_min_samples = min_samples

# Print the results
print("Silhouette Scores for DBSCAN Clustering (eps, min_samples):")
for (eps, min_samples), score in dbscan_silhouette_results.items():
    print(f"  eps = {eps:.1f}, min_samples = {min_samples}, Silhouette Score = {score:.4f}")

print(f"\nBest DBSCAN Model:")
print(f"  Optimal eps = {best_dbscan_eps:.1f}")
print(f"  Optimal min_samples = {best_dbscan_min_samples}")
print(f"  Highest Silhouette Score = {best_dbscan_score:.4f}")

"""### Menerapkan Model DBSCAN Terbaik dan Visualisasi

Berdasarkan Skor Silhouette, kita sekarang akan menerapkan model DBSCAN terbaik dan memvisualisasikan hasilnya menggunakan PCA. Titik *noise* akan direpresentasikan dengan warna yang berbeda.
"""

# Apply DBSCAN with the best parameters
best_dbscan = DBSCAN(eps=best_dbscan_eps, min_samples=best_dbscan_min_samples)
df['cluster_dbscan'] = best_dbscan.fit_predict(df_scaled)

print(f"DBSCAN applied with eps={best_dbscan_eps:.1f} and min_samples={best_dbscan_min_samples}.")
print("\nFirst 5 rows of the dataset with DBSCAN cluster labels:")
display(df.head())

# Prepare data for PCA visualization (re-using df_pca from K-Means visualization for consistency)
df_pca['cluster'] = df['cluster_dbscan']

# Plotting the PCA results for DBSCAN Clustering
plt.figure(figsize=(10, 8))
sns.scatterplot(
    x='Principal Component 1',
    y='Principal Component 2',
    hue='cluster',
    palette='tab10', # Using a different palette for potentially more clusters + noise
    data=df_pca,
    s=100,
    alpha=0.7,
    edgecolor='w'
)
plt.title(f'DBSCAN Clustering (eps={best_dbscan_eps:.1f}, min_samples={best_dbscan_min_samples}) Visualization with PCA')
plt.xlabel('Principal Component 1')
plt.ylabel('Principal Component 2')
plt.grid(True)
plt.legend(title='Cluster')
plt.show()

"""### Ringkasan Hasil Klastering DBSCAN

Berdasarkan analisis, konfigurasi optimal untuk Klastering DBSCAN adalah:

*   **`eps` Optimal:** 0.3
*   **`min_samples` Optimal:** 9
*   **Skor Silhouette Tertinggi:** 0.5133

Ini menunjukkan bahwa dengan parameter-parameter ini, DBSCAN mengidentifikasi klaster dan titik *noise*. Visualisasi menunjukkan klaster-klaster ini, dengan titik *noise* (berlabel -1) biasanya muncul sebagai titik-titik terisolasi.

### Inferensi dari Klastering DBSCAN Optimal
"""

import pandas as pd
from sklearn.preprocessing import StandardScaler
from sklearn.cluster import DBSCAN

# Ensure df is defined
try:
    df.head()
except NameError:
    print("DataFrame 'df' not found. Reloading...")
    df = pd.read_csv('/content/drive/MyDrive/ML_MID/wellnes1.csv', sep=';')

# Ensure selected_features is defined
try:
    _ = selected_features
except NameError:
    print("Variable 'selected_features' not found. Redefining...")
    selected_features = ['stress_level_0_10', 'productivity_0_100', 'sleep_quality_1_5', 'screen_time_hours']

# Ensure df_scaled and df['cluster_dbscan'] are defined for DBSCAN analysis
try:
    df_scaled.head()
    _ = df['cluster_dbscan']
except (NameError, AttributeError, KeyError):
    print("DBSCAN clustering results not found. Re-applying DBSCAN...")
    scaler = StandardScaler()
    df_selected = df[selected_features]
    df_scaled = scaler.fit_transform(df_selected)

    # Optimal parameters from previous analysis (cell 75233641 output)
    best_dbscan_eps = 0.3
    best_dbscan_min_samples = 9

    best_dbscan = DBSCAN(eps=best_dbscan_eps, min_samples=best_dbscan_min_samples)
    df['cluster_dbscan'] = best_dbscan.fit_predict(df_scaled)


print('Mean values of features per DBSCAN cluster:')
# We need to include 'mental_wellness_index_0_100' in the groupby for analysis
display(df.groupby('cluster_dbscan')[selected_features + ['mental_wellness_index_0_100']].mean().round(2))

# Detailed analysis for DBSCAN clusters
cluster_dbscan_summary = df.groupby('cluster_dbscan')[selected_features + ['mental_wellness_index_0_100']].mean().round(2)

# Calculate overall mean for comparison
all_features_for_comparison = selected_features + ['mental_wellness_index_0_100']
overall_means = df[all_features_for_comparison].mean().round(2)

print('\nDetailed Interpretation of DBSCAN Clusters:')
for i, row in cluster_dbscan_summary.iterrows():
    if i == -1:
        print(f'\n--- Noise Points (Cluster {i}) ---')
        print("These points did not fit into any dense cluster and are considered outliers or noise.\n")
    else:
        print(f'\n--- Cluster {i} ---')

    print(f"Average Stress Level: {row['stress_level_0_10']:.2f}")
    print(f"Average Productivity: {row['productivity_0_100']:.2f}")
    print(f"Average Sleep Quality (1-5): {row['sleep_quality_1_5']:.2f}")
    print(f"Average Screen Time (hours): {row['screen_time_hours']:.2f}")
    print(f"Average Mental Wellness Index (0-100): {row['mental_wellness_index_0_100']:.2f}")

    print("\n--- Comparison to Overall Averages ---")
    for feature in all_features_for_comparison:
        diff = row[feature] - overall_means[feature]
        feature_name_display = feature.replace('_', ' ').title().replace('0 10', '0-10').replace('1 5', '1-5').replace('0 100', '0-100')
        if diff > 0:
            print(f"{feature_name_display}: {row[feature]:.2f} (Higher than overall average by {abs(diff):.2f})")
        elif diff < 0:
            print(f"{feature_name_display}: {row[feature]:.2f} (Lower than overall average by {abs(diff):.2f})")
        else:
            print(f"{feature_name_display}: {row[feature]:.2f} (Same as overall average)")

    if i != -1:
        # Provide a more detailed interpretation based on the values for actual clusters
        if row['mental_wellness_index_0_100'] > 70:
            print("This cluster generally exhibits high mental wellness, likely supported by low stress, good productivity, and quality sleep.")
        elif row['mental_wellness_index_0_100'] > 50:
            print("This cluster generally exhibits moderate mental wellness. They might manage stress well and maintain decent productivity and sleep.")
        else:
            print("This cluster generally exhibits lower mental wellness, often associated with higher stress, reduced productivity, and poor sleep.")

        if row['stress_level_0_10'] > 7:
            print("High stress levels are a significant characteristic of this group.")
        elif row['stress_level_0_10'] < 4:
            print("Low stress levels contribute positively to the well-being of this group.")

        if row['productivity_0_100'] > 70:
            print("High productivity is observed, suggesting effectiveness and engagement.")
        elif row['productivity_0_100'] < 40:
            print("Lower productivity is noted, potentially indicating challenges in focus or motivation.")

        if row['sleep_quality_1_5'] > 3:
            print("Good sleep quality is a strong indicator of mental and physical health in this group.")
        elif row['sleep_quality_1_5'] < 2:
            print("Poor sleep quality is a critical issue for this group, impacting overall well-being.")

"""### Inferensi Akhir dari Model Klastering Terbaik: Klastering Aglomeratif (K=2, Linkage='average')

Berdasarkan analisis komprehensif kami, Klastering Aglomeratif dengan **K=2** dan **'average' linkage** muncul sebagai model optimal, menghasilkan Skor Silhouette tertinggi **0.5662**. Ini menunjukkan bahwa model ini memberikan klaster yang paling berbeda dan terpisah dengan baik, menawarkan wawasan yang lebih jelas tentang hubungan antara fitur-fitur yang dipilih dan kesejahteraan mental. Mari kita selami karakteristik dari dua klaster menonjol ini.
"""

print('Nilai rata-rata fitur per klaster Aglomeratif (K=3):')
display(df.groupby('cluster_agglomerative_k3')[selected_features + ['mental_wellness_index_0_100']].mean().round(2))

# Detailed analysis for Agglomerative K=3 clusters
cluster_agg_k3_summary = df.groupby('cluster_agglomerative_k3')[selected_features + ['mental_wellness_index_0_100']].mean().round(2)

# Calculate overall mean for comparison
all_features_for_comparison = selected_features + ['mental_wellness_index_0_100']
overall_means = df[all_features_for_comparison].mean().round(2)

print('\nInterpretasi Detail Klaster Aglomeratif (K=3):')
for i, row in cluster_agg_k3_summary.iterrows():
    print(f'\n--- Klaster {i} ---')
    print(f"Average Stress Level: {row['stress_level_0_10']:.2f}")
    print(f"Average Productivity: {row['productivity_0_100']:.2f}")
    print(f"Average Sleep Quality (1-5): {row['sleep_quality_1_5']:.2f}")
    print(f"Average Screen Time (hours): {row['screen_time_hours']:.2f}")
    print(f"Average Mental Wellness Index (0-100): {row['mental_wellness_index_0_100']:.2f}")

    print("\n--- Perbandingan dengan Rata-rata Keseluruhan ---")
    for feature in all_features_for_comparison:
        diff = row[feature] - overall_means[feature]
        feature_name_display = feature.replace('_', ' ').title().replace('0 10', '0-10').replace('1 5', '1-5').replace('0 100', '0-100')
        if diff > 0:
            print(f"{feature_name_display}: {row[feature]:.2f} (Lebih tinggi dari rata-rata keseluruhan sebesar {abs(diff):.2f})")
        elif diff < 0:
            print(f"{feature_name_display}: {row[feature]:.2f} (Lebih rendah dari rata-rata keseluruhan sebesar {abs(diff):.2f})")
        else:
            print(f"{feature_name_display}: {row[feature]:.2f} (Sama dengan rata-rata keseluruhan)")

    # Provide a more detailed interpretation based on the values
    if row['mental_wellness_index_0_100'] > 70:
        print("Klaster ini umumnya menunjukkan kesehatan mental yang tinggi, kemungkinan didukung oleh stres rendah, produktivitas baik, dan kualitas tidur yang baik.")
    elif row['mental_wellness_index_0_100'] > 50:
        print("Klaster ini umumnya menunjukkan kesehatan mental yang moderat. Mereka mungkin mengelola stres dengan baik dan mempertahankan produktivitas serta tidur yang layak.")
    else:
        print("Klaster ini umumnya menunjukkan kesehatan mental yang lebih rendah, seringkali terkait dengan stres yang lebih tinggi, produktivitas yang berkurang, dan tidur yang buruk.")

    if row['stress_level_0_10'] > 7:
        print("Tingkat stres yang tinggi merupakan karakteristik signifikan dari kelompok ini.")
    elif row['stress_level_0_10'] < 4:
        print("Tingkat stres yang rendah berkontribusi positif terhadap kesejahteraan kelompok ini.")

    if row['productivity_0_100'] > 70:
        print("Produktivitas yang tinggi diamati, menunjukkan efektivitas dan keterlibatan.")
    elif row['productivity_0_100'] < 40:
        print("Produktivitas yang lebih rendah dicatat, berpotensi menunjukkan tantangan dalam fokus atau motivasi.")

    if row['sleep_quality_1_5'] > 3:
        print("Kualitas tidur yang baik merupakan indikator kuat kesehatan mental dan fisik dalam kelompok ini.")
    elif row['sleep_quality_1_5'] < 2:
        print("Kualitas tidur yang buruk merupakan masalah kritis bagi kelompok ini, memengaruhi kesejahteraan secara keseluruhan.")

"""BEST

### Mengeksplorasi Model Klastering Aglomeratif Terbaik Kedua (K=3, Linkage='average')

Meskipun K=2 dengan 'average' linkage memberikan Skor Silhouette tertinggi, mari kita jelajahi konfigurasi terbaik berikutnya untuk Klastering Aglomeratif, yaitu K=3 dengan 'average' linkage (Skor Silhouette: 0.4368). Ini akan memberikan perspektif alternatif tentang struktur inheren data.
"""

import numpy as np

# Apply Agglomerative Clustering with K=3 and 'average' linkage
agg_clustering_k3 = AgglomerativeClustering(n_clusters=3, linkage='average')
df['cluster_agglomerative_k3'] = agg_clustering_k3.fit_predict(df_scaled)

print(f"Agglomerative Clustering applied with K=3 and linkage='average'.")
print("\nFirst 5 rows of the dataset with Agglomerative K=3 cluster labels:")
display(df.head())

# Calculate and display the Silhouette Score for K=3
silhouette_score_k3 = silhouette_score(df_scaled, df['cluster_agglomerative_k3'])
print(f"\nSilhouette Score for Agglomerative Clustering with K=3: {silhouette_score_k3:.4f}")

# Prepare data for PCA visualization
pca_k3 = PCA(n_components=2)
df_pca_agg_k3 = pca_k3.fit_transform(df_scaled)
df_pca_agg_k3 = pd.DataFrame(data=df_pca_agg_k3, columns=['Principal Component 1', 'Principal Component 2'])
df_pca_agg_k3['cluster'] = df['cluster_agglomerative_k3']

# Plotting the PCA results for Agglomerative Clustering with K=3
plt.figure(figsize=(10, 8))
sns.scatterplot(
    x='Principal Component 1',
    y='Principal Component 2',
    hue='cluster',
    palette='viridis',
    data=df_pca_agg_k3,
    s=100,
    alpha=0.7,
    edgecolor='w'
)
plt.title(f'Agglomerative Clustering (K=3, Linkage=average) Visualization with PCA')
plt.xlabel('Principal Component 1')
plt.ylabel('Principal Component 2')
plt.grid(True)
plt.legend(title='Cluster')
plt.show()

"""### Inferensi dari Klastering Aglomeratif (K=3, Linkage='average')

Mari kita analisis karakteristik dari ketiga klaster Aglomeratif ini dan bagaimana mereka berkaitan dengan kesehatan mental.

### Kesimpulan Aglomeratif Klastering (K=3, Linkage='average')

Analisis klastering Aglomeratif dengan K=3 dan metode linkage 'average' menunjukkan pembagian data menjadi tiga kelompok utama, yang masing-masing memiliki karakteristik unik terkait kesehatan mental:

*   **Klaster 0: Kelompok Stres Tinggi & Kesejahteraan Mental Rendah**
    *   **Kesehatan Mental (Rata-rata 12.76):** Menunjukkan kesehatan mental yang sangat rendah.
    *   **Level Stres (Rata-rata 8.93):** Tingkat stres yang sangat tinggi.
    *   **Produktivitas (Rata-rata 48.89):** Produktivitas rendah.
    *   **Kualitas Tidur (Rata-rata 1.21):** Kualitas tidur sangat buruk.
    *   **Waktu Layar (Rata-rata 9.67 jam):** Waktu layar tinggi.
    *   **Interpretasi:** Klaster ini mengidentifikasi individu yang menghadapi tantangan signifikan dalam kesehatan mental mereka, ditandai dengan stres ekstrem, produktivitas yang terganggu, kualitas tidur yang sangat buruk, dan waktu layar yang tinggi. Kombinasi faktor-faktor ini menciptakan lingkaran setan yang memperparah kondisi mental mereka.

*   **Klaster 1: Kelompok Sehat Mental dan Berprestasi**
    *   **Kesehatan Mental (Rata-rata 84.71):** Menunjukkan kesehatan mental yang tinggi.
    *   **Level Stres (Rata-rata 1.64):** Tingkat stres yang sangat rendah.
    *   **Produktivitas (Rata-rata 98.06):** Produktivitas yang sangat tinggi.
    *   **Kualitas Tidur (Rata-rata 3.29):** Kualitas tidur yang baik.
    *   **Waktu Layar (Rata-rata 4.07 jam):** Waktu layar rendah.
    *   **Interpretasi:** Kelompok ini merepresentasikan individu dengan kesehatan mental yang sangat baik, didukung oleh manajemen stres yang efektif, tingkat produktivitas yang luar biasa, kualitas tidur yang optimal, dan waktu layar yang rendah. Mereka adalah contoh bagaimana faktor-faktor ini saling mendukung untuk mencapai kesejahteraan mental yang tinggi.

*   **Klaster 2: Kelompok Produktif Moderat**
    *   **Kesehatan Mental (Rata-rata 49.86):** Menunjukkan kesehatan mental yang moderat.
    *   **Level Stres (Rata-rata 5.08):** Tingkat stres menengah.
    *   **Produktivitas (Rata-rata 75.70):** Produktivitas tinggi.
    *   **Kualitas Tidur (Rata-rata 2.09):** Kualitas tidur cenderung kurang baik.
    *   **Waktu Layar (Rata-rata 6.46 jam):** Waktu layar moderat.
    *   **Interpretasi:** Kelompok ini mungkin terdiri dari individu yang produktif namun masih bergumul dengan stres yang berdampak pada kualitas tidur dan secara tidak langsung mempengaruhi kesehatan mental mereka secara keseluruhan.

Analisis K=3 ini memberikan wawasan yang lebih rinci tentang spektrum kesehatan mental, memisahkan antara perjuangan moderat dan berat, sambil tetap menyoroti kelompok yang memiliki kesehatan mental yang sangat baik.
"""

print('Mean values of features per Agglomerative cluster (K=3):')
display(df.groupby('cluster_agglomerative_k3')[selected_features + ['mental_wellness_index_0_100']].mean().round(2))

# Detailed analysis for Agglomerative K=3 clusters
cluster_agg_k3_summary = df.groupby('cluster_agglomerative_k3')[selected_features + ['mental_wellness_index_0_100']].mean().round(2)

# Calculate overall mean for comparison
all_features_for_comparison = selected_features + ['mental_wellness_index_0_100']
overall_means = df[all_features_for_comparison].mean().round(2)

print('\nDetailed Interpretation of Agglomerative Clusters (K=3):')
for i, row in cluster_agg_k3_summary.iterrows():
    print(f'\n--- Cluster {i} ---')
    print(f"Average Stress Level: {row['stress_level_0_10']:.2f}")
    print(f"Average Productivity: {row['productivity_0_100']:.2f}")
    print(f"Average Sleep Quality (1-5): {row['sleep_quality_1_5']:.2f}")
    print(f"Average Screen Time (hours): {row['screen_time_hours']:.2f}")
    print(f"Average Mental Wellness Index (0-100): {row['mental_wellness_index_0_100']:.2f}")

    print("\n--- Comparison to Overall Averages ---")
    for feature in all_features_for_comparison:
        diff = row[feature] - overall_means[feature]
        feature_name_display = feature.replace('_', ' ').title().replace('0 10', '0-10').replace('1 5', '1-5').replace('0 100', '0-100')
        if diff > 0:
            print(f"{feature_name_display}: {row[feature]:.2f} (Higher than overall average by {abs(diff):.2f})")
        elif diff < 0:
            print(f"{feature_name_display}: {row[feature]:.2f} (Lower than overall average by {abs(diff):.2f})")
        else:
            print(f"{feature_name_display}: {row[feature]:.2f} (Same as overall average)")

    # Provide a more detailed interpretation based on the values
    if row['mental_wellness_index_0_100'] > 70:
        print("This cluster generally exhibits high mental wellness, likely supported by low stress, good productivity, and quality sleep.")
    elif row['mental_wellness_index_0_100'] > 50:
        print("This cluster generally exhibits moderate mental wellness. They might manage stress well and maintain decent productivity and sleep.")
    else:
        print("This cluster generally exhibits lower mental wellness, often associated with higher stress, reduced productivity, and poor sleep.")

    if row['stress_level_0_10'] > 7:
        print("High stress levels are a significant characteristic of this group.")
    elif row['stress_level_0_10'] < 4:
        print("Low stress levels contribute positively to the well-being of this group.")

    if row['productivity_0_100'] > 70:
        print("High productivity is observed, suggesting effectiveness and engagement.")
    elif row['productivity_0_100'] < 40:
        print("Lower productivity is noted, potentially indicating challenges in focus or motivation.")

    if row['sleep_quality_1_5'] > 3:
        print("Good sleep quality is a strong indicator of mental and physical health in this group.")
    elif row['sleep_quality_1_5'] < 2:
        print("Poor sleep quality is a critical issue for this group, impacting overall well-being.")

"""**Pseudo** **Predict**

dikarenakan infernce di dalam clustering itu abu-abu, maka dilkukan pseudo predict dimana dicocokan threshold tiap kelas yg telah ada dan disimpulkan masuk dalam kelas apa. Hal ini digaris bawahi bahwa dimasukkan data sesuai dengan data yg dimodel, diakrenakan jika jauh dari data asli, maka hasil tidak akan akurat, dan diharuskan untuk melakukan pemodelan ulang dengan menambah data baru. Sehingga infrence sangat aman dalam clustering adalah dengan melakukan analisis dan pemaaran deskriptif hubungan antar fitur yg telah dimasukkan ke dalam laporan dan PPT


"""

# Ambil centroid dari hasil clustering
import numpy as np

# ambil label
labels = df['cluster_agglomerative_k3'].values

# hitung centroid tiap cluster
centroids = []
for i in range(3):
    cluster_points = df_scaled[labels == i]
    centroids.append(cluster_points.mean(axis=0))

centroids = np.array(centroids)

print("Centroids:")
print(centroids)

# buat fungsi inference
from scipy.spatial.distance import cdist

def predict_agglomerative(data_baru, centroids):
    data_baru = np.array(data_baru).reshape(1, -1)
    distances = cdist(data_baru, centroids)

    cluster = distances.argmin()
    min_distance = distances.min()

    return cluster, min_distance

from sklearn.preprocessing import StandardScaler

# Re-initialize and fit the scaler on the selected features to ensure correct feature count
scaler = StandardScaler()
scaler.fit(df_selected)

data_baru = [[7, 50, 2, 8]]
data_baru_scaled = scaler.transform(data_baru)

cluster, distance = predict_agglomerative(data_baru_scaled[0], centroids)

print(f"New data assigned to Cluster: {cluster}")
print(f"Distance to Centroid: {distance:.2f}")

"""### Perbandingan Model Klastering

Dari eksperimen yang telah dilakukan, kita dapat menyimpulkan perbandingan model sebagai berikut:

*   **K-Means:** Meskipun skor Silhouette tertinggi tercapai pada K=2 (0.4627), kita mengeksplorasi K=4 (0.3859) untuk analisis lebih lanjut. K-Means menghasilkan klaster yang cenderung berbentuk bulat dan berukuran sama.

*   **Klastering Aglomeratif:** Model terbaik ditemukan dengan K=2 dan metode linkage 'average', mencapai skor Silhouette tertinggi sebesar 0.5662, menunjukkan pemisahan klaster yang sangat baik. Eksplorasi tambahan dengan K=3 (0.4368) juga memberikan wawasan yang berharga tentang struktur data.

*   **DBSCAN:** Model DBSCAN terbaik menggunakan `eps` 0.3 dan `min_samples` 9, dengan skor Silhouette 0.5133. DBSCAN unggul dalam menemukan klaster berbentuk arbitrer dan mengidentifikasi titik *noise*, yang tidak terdeteksi oleh algoritma lain.

### Konversi Klastering Menjadi Model Klasifikasi

Kita akan menggunakan hasil klastering Aglomeratif dengan K=3 sebagai label target untuk melatih model klasifikasi. Ini akan membantu kita melihat seberapa baik fitur yang dipilih dapat memprediksi keanggotaan klaster tersebut.
"""
